### ISSUE TITLE
Hover tooltips for Tailwind classes show duplicate tips

### ISSUE THREAD

**Issue by retailonline** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#17]
When hovering over a class, the tooltip shows the same tips four times.

![hover-tooltips](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/25500812/d55a3492-3b7d-44ca-ac08-cf1419dfb438)

**Comment by theron-wang** [comment]
This should be fixed with the latest update. Thank you for reporting this bug!

**Comment by retailonline** [comment]
It's still the same problem for me. I've downloaded your updated version, disabled and enabled the extension, uninstalled and reinstalled it, but the same four duplicate rows still show up when hovering.
I'm using the latest Visual Studio version, 17.7.3.

![screen](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/25500812/f6fb2832-9b72-4646-a757-574121b606d1)

**Comment by theron-wang** [comment]
Sorry, do you think you could provide your `tailwind.config.js` so I can reproduce this?

**Comment by retailonline** [comment]
Hi again!

For you information, after updating to you latest build this happen:

![Untitled-2](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/25500812/c88e831d-f84d-4d62-a943-1b5a871c3ea9)

**Comment by theron-wang** [comment]
Ok, thanks for letting me know. I’ll see what I can do once I have some time.

**Comment by theron-wang** [comment]
I was unable to reproduce either one of the issues, but I did make some changes to try to fix the issue.

Especially regarding the performance issue, I changed how the package was initialized, but if you still encounter significant performance hits, please let me know.

Thanks!

**Comment by retailonline** [comment]
After installing your new update, everything is fine: no duplicated tooltips when hovering over a class, nor is Visual Studio complaining about slow performance. 
Thank you for creating this awesome extension!

![Untitled-2](https://github.com/theron-wang/VS2022-Editor-Support-for-Tailwind-CSS/assets/25500812/6038cafa-2ef7-4673-a537-b181e261a3a6)

**Comment by theron-wang** [comment]
No problem! Happy to hear that.
