### ISSUE TITLE
Extension failed to load

### ISSUE THREAD

**Issue by caio-delgado** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#71]
Hello! Extension started to crash. This is the extensions output dump:

System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializer' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
   at System.Text.Json.JsonSerializer..cctor()
   --- End of inner exception stack trace ---
   at System.Text.Json.JsonSerializerOptions.GetOrCreateDefaultOptionsInstance()
   at System.Text.Json.JsonSerializerOptions.get_Default()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.DeserializeAsync[TValue](Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()

**Comment by theron-wang** [comment]
Thanks! I believe this is the same error as #68 (however, that was with `Microsoft.Bcl.AsyncInterfaces`). I've bundled all `System.Text.Json` DLLs in the extension in 1.5.5.1 so this should be fixed.

**Comment by caio-delgado** [comment]
I’ve updated but it’s still throwing the same exception. On a side note it’s crashing on VS 2022 17.2.5. I’ve installed another instance of VS2022 17.9.5 and it’s working on that one so I’m good. Thanks for keeping this extension working for us!

**Comment by theron-wang** [comment]
Alright, thanks for letting me know! I initially missed the `Version=4.0.1.2` portion of the error message; the extension ships with `4.5.5`, so that could be the issue. I'll take a look into this in the next release.

**Comment by theron-wang** [comment]
@caio-delgado In 1.5.5.2 I made some small changes (fixed some versioning typos) which should fix this issue. If you are able to, could you check to see if it works in the buggy instance of VS? Thanks.

**Comment by caio-delgado** [comment]
I updated the extension and it started throwing this now:

System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Build.TailwindBuildProcess.<InitializeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.TailwindCSSIntellisensePackage.<>c__DisplayClass8_0.<<FolderOpened>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Build.TailwindBuildProcess.<InitializeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.TailwindCSSIntellisensePackage.<>c__DisplayClass8_0.<<FolderOpened>b__0>d.MoveNext()

AVI: o log de associações de assembly está desativado.
Para ativar o log de  falhas de assembly, defina o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Observação: há alguma penalidade para o desempenho associada ao log de falha de associação de assembly.
Para desativar esse recurso, remova o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog].
<---

System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Build.TailwindBuildProcess.<InitializeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.TailwindCSSIntellisensePackage.<>c__DisplayClass8_0.<<FolderOpened>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Build.TailwindBuildProcess.<InitializeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.TailwindCSSIntellisensePackage.<>c__DisplayClass8_0.<<FolderOpened>b__0>d.MoveNext()

AVI: o log de associações de assembly está desativado.
Para ativar o log de  falhas de assembly, defina o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Observação: há alguma penalidade para o desempenho associada ao log de falha de associação de assembly.
Para desativar esse recurso, remova o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog].
<---

System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Build.TailwindBuildProcess.<InitializeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.TailwindCSSIntellisensePackage.<>c__DisplayClass8_0.<<FolderOpened>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. O sistema não pode encontrar o arquivo especificado.
File name: 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetDefaultSimpleConverters()
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver..ctor(Boolean mutable)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.RootDefaultInstance()
   at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<OverrideSettingsAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Settings.SettingsProvider.<GetSettingsAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Build.TailwindBuildProcess.<InitializeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.TailwindCSSIntellisensePackage.<>c__DisplayClass8_0.<<FolderOpened>b__0>d.MoveNext()

AVI: o log de associações de assembly está desativado.
Para ativar o log de  falhas de assembly, defina o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Observação: há alguma penalidade para o desempenho associada ao log de falha de associação de assembly.
Para desativar esse recurso, remova o valor do Registro [HKLM\Software\Microsoft\Fusion!EnableLog].
<---

**Comment by theron-wang** [comment]
@caio-delgado Thanks so much - this log helps a lot! I believe that since the current version of `System.Text.Json` uses .NET Standard 2.1, and VS ships with .NET Framework (I believe up to Standard 2.0 supports Framework, but 2.1 does not), these errors are being thrown. I'll downgrade the version to one that works when I get the chance; hopefully that will fix the issue.

**Comment by caio-delgado** [comment]
No trouble! Just gimme a howler when you need more testing.

**Comment by theron-wang** [comment]
@caio-delgado Thanks :) If you are able to, could you test 1.5.6? Hopefully this one will finally fix the issue.

**Comment by caio-delgado** [comment]
That one fixed it!

**Comment by theron-wang** [comment]
Great! Thanks so much for your help.
