### ISSUE TITLE
Adding typography plugin breaks intellisense

### ISSUE THREAD

**Issue by skttl** [theron-wang/VS2022-Editor-Support-for-Tailwind-CSS#87]
When I add the official typography plugin to my config, I suddenly don't get Intellisense on my extended theme values.

As an example:

Here I have a quite basic config file, with one extended color. Intellisense works as expected:
![image](https://github.com/user-attachments/assets/8f500f17-2abd-4f8c-b77e-624da496320c)

If I then add the typography plugin (and another color), (and close and reopen the cshtml file), I don't get intellisense for the new color.

![image](https://github.com/user-attachments/assets/028f8dea-d4cd-4998-bd81-37db2792353e)

As soon as I remove the plugin (and close and reopen the cshtml), intellisense works as expected
![image](https://github.com/user-attachments/assets/40d3adbe-b6b3-4af7-a7bf-c8841e495d9e)

I've also tried adding a custom plugin as per the tailwind docs, and that seems to work as expected
![image](https://github.com/user-attachments/assets/17dc2e84-3a22-49fb-990d-3d5b66c62655)

**Comment by theron-wang** [comment]
@skttl Sorry, I wasn't able to reproduce this bug; is there an error being logged in the Extensions output pane by any chance? Thanks.

**Comment by skttl** [comment]
Thanks for getting back.

I get this message:

```
System.InvalidOperationException: Error occurred while parsing configuration file: node:internal/modules/cjs/loader:1145
  const err = new Error(message);
              ^
Error: Cannot find module 'tailwindcss/defaultTheme'
Require stack:
- c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\el0qbr2n.erb\Resources\parser.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.require (c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\el0qbr2n.erb\Resources\parser.js:37:36)
    at require (node:internal/modules/helpers:179:18)
    at theme (c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\el0qbr2n.erb\Resources\parser.js:145:34)
    at C:\Workspaces\OrifarmBaseline\OrifarmBaseline\Presentation\Website\node_modules\@tailwindcss\typography\src\index.js:74:23
    at handler (c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\el0qbr2n.erb\Resources\parser.js:16:64)
    at c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\el0qbr2n.erb\Resources\parser.js:181:25
    at Array.forEach (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\users\\skttl\\appdata\\local\\microsoft\\visualstudio\\17.0_c7615a97\\extensions\\el0qbr2n.erb\\Resources\\parser.js'
  ]
}
Node.js v20.15.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesAsync>d__47.MoveNext()


```

Seems like it has to do with getting values from the default theme

**Comment by theron-wang** [comment]
@skttl I believe this was related to the extension override of the `NODE_PATH` environment variable; this should be addressed in 1.7.2. If not, please let me know!

**Comment by skttl** [comment]
Hi @theron-wang 

I still get the error on 1.8.0

```
System.InvalidOperationException: Error occurred while parsing configuration file: node:internal/modules/cjs/loader:1145
  const err = new Error(message);
              ^
Error: Cannot find module 'tailwindcss/defaultTheme'
Require stack:
- c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\bunpbc4l.o13\Resources\parser.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Module.require (c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\bunpbc4l.o13\Resources\parser.js:37:36)
    at require (node:internal/modules/helpers:179:18)
    at theme (c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\bunpbc4l.o13\Resources\parser.js:145:34)
    at containerQueries (C:\Workspaces\Dinex\Dinex\Presentation\Website\node_modules\@tailwindcss\container-queries\dist\index.js:18:28)
    at handler (c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\bunpbc4l.o13\Resources\parser.js:26:44)
    at c:\users\skttl\appdata\local\microsoft\visualstudio\17.0_c7615a97\extensions\bunpbc4l.o13\Resources\parser.js:181:25
    at Array.forEach (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\users\\skttl\\appdata\\local\\microsoft\\visualstudio\\17.0_c7615a97\\extensions\\bunpbc4l.o13\\Resources\\parser.js'
  ]
}
Node.js v20.15.0
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigJsonNodeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.ConfigFileParser.<GetConfigurationAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TailwindCSSIntellisense.Configuration.CompletionConfiguration.<ReloadCustomAttributesAsync>d__47.MoveNext()

```

I also tried removing everything but a single plugin in my config, so I ended up with this:

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  plugins: [
    require('@tailwindcss/container-queries')
  ]
};
```

without luck.

Could it be something with me local node installation?

**Comment by skttl** [comment]
Installing tailwindcss globally (`npm i -g tailwindcss`) seems to fix it, but can we make it not require having tailwindcss installed globally?

Also theres a bug in the container-queries plugin, that surfaces, when tailwindcss is installed globally, but thats something that needs fixing in that plugin :)

**Comment by theron-wang** [comment]
@skttl Sorry for the delay. The root of the issue appears to be with the extension's setting of `NODE_PATH` to allow for modules to be resolved due to the external location of `parser.js`. In the last release, configuration parsing sets `NODE_PATH` to the `node_modules` folder where your `tailwind.config.js` file is located, as well as to the global installation of `node_modules` (`npm root -g`). I'm not sure exactly why the error occurs in your case, but I was able to reproduce similar behavior when failing to set `NODE_PATH` correctly. 

Perhaps the issue is the location of your configuration file - is it located in the same directory as `node_modules`? Thanks.

**Comment by skttl** [comment]
Hi @theron-wang 

Thanks for getting back! That might be the issue.

I have a folder structure like this:

- /node_modules
- /UI
  - /CSS
    - /tailwind.config.js
    - /main.css
- /package.json

Same goes for v4 projects, those just don't have the js config file.

Maybe it could be made to find the closest package.json from the config file location, by looking up in the tree until it finds one, and then resolve the node_modules folder from there.

So in my case a flow like this (hope it makes sense)
```
 - found config file in /UI/CSS/tailwind.config.js
 - did not find package.json in /UI/CSS
 - did not find package.json in /UI
 - found package.json in /
 - node_modules is in /node_modules
```

**Comment by theron-wang** [comment]
@skttl Thank you - I was able to reproduce it. I implemented the flow as you suggested and it should be fixed in 1.9.2 :)
